/**
 * [INPUT]: 依赖 Node.js fs/path 与 src 下的规范包契约、组件采集、目标配置、匹配器及 UI 源码
 * [OUTPUT]: 对外生成 dist/code.js 和 dist/ui.html，供 manifest.json 加载
 * [POS]: scripts 的无依赖构建器，以确定顺序拼接运行时代码并隔离生成产物
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(scriptDir, "..");
const sourceDir = path.join(rootDir, "src");
const outputDir = path.join(rootDir, "dist");

const [catalog, components, profiles, matcher, tokenMatcher, textCatalog, tokenCatalog, code, uiTemplate, uiCss, uiJs] = await Promise.all([
  readFile(path.join(sourceDir, "library-catalog.js"), "utf8"),
  readFile(path.join(sourceDir, "component-catalog.js"), "utf8"),
  readFile(path.join(sourceDir, "design-system-profile.js"), "utf8"),
  readFile(path.join(sourceDir, "matcher.js"), "utf8"),
  readFile(path.join(sourceDir, "token-matcher.js"), "utf8"),
  readFile(path.join(sourceDir, "vdesign-styles.js"), "utf8"),
  readFile(path.join(sourceDir, "vdesign-tokens.js"), "utf8"),
  readFile(path.join(sourceDir, "code.js"), "utf8"),
  readFile(path.join(sourceDir, "ui.html"), "utf8"),
  readFile(path.join(sourceDir, "ui.css"), "utf8"),
  readFile(path.join(sourceDir, "ui.js"), "utf8"),
]);

const ui = uiTemplate
  .replace("/*__INLINE_CSS__*/", uiCss)
  .replace("/*__INLINE_JS__*/", uiJs);

await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });
await Promise.all([
  writeFile(
    path.join(outputDir, "code.js"),
    `/* Generated by scripts/build.mjs. Edit src/, not dist/. */\n${catalog}\n${components}\n${profiles}\n${matcher}\n${tokenMatcher}\n${textCatalog}\n${tokenCatalog}\n${code}\n`,
    "utf8",
  ),
  writeFile(path.join(outputDir, "ui.html"), ui, "utf8"),
]);

process.stdout.write("Built dist/code.js and dist/ui.html\n");
